name: PipelineTest2

on: [push]

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Check out project
      - name: Run a one-line
      - run: echo Test MedicalSystem
